public enum SceneName {
    NONE,
    FOREST_SPAWN_ROOM = 1000,
    FOREST_LEFT_ONE,
    AIR_ENTRY_ROOM,
    FOREST_LEFT_TWO
    /* TEST_SPAWN_ROOM = 1000,
    TEST_VERTICAL_JUMP,
    TEST_HANGING,
    TEST_WALL_JUMP,
    TEST_FALLING,
    TEST_TRANSITION,
    TEST_HORIZONTAL_JUMP,
    TEST_PUZZLE,
    TEST_LARGE,
    TEST_SAVE, */
};
